cli_flags.go
reporter/datadog_reporter.go

`collection-agent` is treated as the Datadog agent URL and profiling endpoint is appended to it.

Handle "collection-agent" argument as Datadog agent URL

---

Dockerfile

* Avoid setting GOPATH in docker image
Setting GOPATH to point inside agent directory has some undesirable side effects, such as make `go test ./...` fail ( because it tries to execute tests in ./go directory).
* Add a `build` user
Add a `build` user  and run container with this user by default.
This allows mounting local agent directory in the docker container while still the right uid permissions.
Allow this user to sudo in order to run the otel agent.

Improve build image

---

libpf/libpf.go
libpf/process/coredump.go
libpf/process/process.go
libpf/process/types.go
processmanager/manager_test.go
processmanager/processinfo.go
reporter/datadog_reporter.go
reporter/iface.go
reporter/otlp_reporter.go
reporter/reporter.go
tracehandler/tracehandler.go
tracehandler/tracehandler_test.go
utils/coredump/coredump.go

Add a root frame with the path of the executable when the information is available.
This is done in three steps. 
First, we need to provide the reporter with the PID <-> Executable path name mapping. This is done by:
* Adding a `GetExecutablePath()` on the process object, that either returns the main executable for a core dump, or reads `/proc/pid/exe` for live processes)
* On `SynchronizeProcess`, the process manager will call `ProcessMetadata` indicating which pid has which exec name.
* On the reporter we add an LRU that contains the PID <-> Executable mapping, that is updated by `ProcessMetadata` calls.
Then we need to have the PID for the sample we're currently producing. This is done by:
* Updating the tracehandler so that it includes the PID in `ReportCountForTrace`
* Updating …

Add root frame with executable path when available (PROF-9924)

---

.gitignore
README.md
docker-compose.yml

add a docker-compose file with the locally built and compiled agent as well as the datadog-agent communicating with each other to make local development more seamless

chore: add a docker-compose file for local development

---

docker-compose.yml
reporter/datadog_reporter.go

permits slicing down the profile by container name, by ensuring we add both a pprof label and tag for container name.
we use container_name instead of containerName as we're currently normalizing the tag to containername, and this leads to a discrepancy between the tag and the pprof label (containerName).
also mount docker.sock locally so that the otel-agent is able to find the container names

datadog-reporter: add container name pprof tag (PROF-9951)

---

reporter/datadog_reporter.go

```
goroutine 378 [running]:
github.com/elastic/otel-profiling-agent/reporter.(*DatadogReporter).getPprofProfile(0xc000852000)
/home/runner/work/otel-profiling-agent/otel-profiling-agent/reporter/datadog_reporter.go:540 +0x27cd
github.com/elastic/otel-profiling-agent/reporter.(*DatadogReporter).reportProfile(0xc000852000, {0x2ff80d0, 0xc0006900a0})
/home/runner/work/otel-profiling-agent/otel-profiling-agent/reporter/datadog_reporter.go:318 +0x55
github.com/elastic/otel-profiling-agent/reporter.StartDatadog.func1()
/home/runner/work/otel-profiling-agent/otel-profiling-agent/reporter/datadog_reporter.go:297 +0x15d
created by github.com/elastic/otel-profiling-agent/reporter.StartDatadog in goroutine 1
/home/runner/work/otel-profiling-agent/otel-profiling-agent/reporter/datadog_reporter.go:287 …
```

datadog-reporter: fix panic when frameTypes is empty

---

containermetadata/containermetadata.go
containermetadata/containermetadata_test.go
docker-compose.yml
libpf/libpf.go
reporter/datadog_reporter.go
reporter/iface.go
reporter/otlp_reporter.go
reporter/reporter.go
tracehandler/tracehandler.go
tracehandler/tracehandler_test.go

Add a default parsing pattern for the cgroup file based on https://github.com/open-telemetry/opentelemetry-go/blob/6a0fa3c911a061198302cd1972c2e1a9e5ffa87f/sdk/resource/container.go#L21 to be able to parse the container ID even when the container metadata environment is not detected.
Export containerID attribute to be able to inject it in the `traceInfo` and also hook this up as a pprof label, and a tag for the dd reporter.
Local profile with working docker metadata and both `container_id` and `container_name` tags:
Local profile with docker metadata off, and only `container_id` tag:

container metadata: add container_id as a label (PROF-9951)

---

host/host.go
libpf/libpf.go
reporter/datadog_reporter.go
reporter/iface.go
reporter/otlp_reporter.go
reporter/reporter.go
support/ebpf/native_stack_trace.ebpf.c
support/ebpf/types.h
tracehandler/tracehandler.go
tracehandler/tracehandler_test.go
tracer/tracer.go

get thread ID from `bpf_get_current_pid_tgid` (based on https://man7.org/linux/man-pages/man7/bpf-helpers.7.html)
and pass it down through the trace to the reporter. attach it to the emitted pprof as a label
Process-agent profile filtered on a thread ID:
Process-agent profile filtered on a process ID (for the same thread ID):

reporter: attach thread ID to emitted profiles (PROF-9959)

---

reporter/datadog_reporter.go

Also rename `comm` label into `thread_name` and add it to custom context. 
Usual label name in other profilers is `thread name` but custom context labels cannot have whitespaces...

[PROF-9960] Use mapping filename instead of comm for function filename

---

main.go

when we fail to initialize the datadog symbol uploader, we set the uploader to nil, which will cause a panic later on when handling a new executable for symbol upload.
this sets the uploader to `symbolication.NewNoopUploader()` when the datadog uploader is set up, but fails to be initialized.

[PROF-10045] uploader: fix segfault on failure to init datadog uploader

---

README.md
docker-compose.yml
libpf/pfelf/file.go
libpf/process/coredump.go
libpf/process/process.go
main.go
processmanager/execinfomanager/manager.go
processmanager/manager.go
processmanager/manager_test.go
processmanager/processinfo.go
symbolication/datadog_uploader.go
symbolication/iface.go
symbolication/uploader.go
tracer/tracer.go
utils/coredump/coredump.go
utils/coredump/storecoredump.go

Upload symbols for executables when symbols are available locally.
By default, this is a no-op. When `DD_EXPERIMENTAL_LOCAL_SYMBOL_UPLOAD` environment variable is set to true, this will kick off the symbol upload logic for each new executable found in a mapping.
The datadog uploader requires setting up `DD_API_KEY` and `DD_SITE`. For now, symbols are only uploaded for executables which contain DWARF data.
I tried keeping changes to `otel-profiling-agent` to a minimum, the main changes requires are:
* Wiring up the uploader in `execinfomanager`, and
* Passing the global file ID to `execinfomanager` (in addition to the host-local ID), to be able to pass it to the uploader, and
* Including the ELF file path in `pfelf.File`, as passed to os.Open (so that we're able to get a file path to feed …

[PROF-9983] Leverage local symbols for otel-profiling-agent

---

symbolication/datadog_uploader.go

While looking at a local run of https://github.com/DataDog/otel-profiling-agent/pull/23 I noticed the following logs (truncated), which come from uploading the local symbols for /usr/bin/docker multiple times.
```
time="2024-06-21T21:12:25.489808710Z" level=info msg="Symbols uploaded successfully for executable: &{Arch:amd64 GNUBuildID:f9e5ec69231b8b8051d58c5998f1ad8211be58af GoBuildID:Q0IBrcoBQipcsw5gRK-x/mopRzMQH1Hw5GPtpymQt/NpuCDZjIVq2xk9eYXtTf/f-lXVQrOOOumMwcdeq-B FileHash:083ce3583a48215bc026386a7edb819f Platform:elf Type:elf_symbol_file fileName:/usr/bin/docker}"
...
time="2024-06-21T21:14:48.123064125Z" level=info msg="Symbols uploaded successfully for executable: &{Arch:amd64 GNUBuildID:f9e5ec69231b8b8051d58c5998f1ad8211be58af …
```

[PROF-10028] Avoid re-uploading already successfully uploaded file

---

README.md
docker-compose.yml
reporter/datadog_reporter.go

Always append `remote_symbols:yes` as a tag in the profiler

reporter: always append remote_symbols:yes tag

---

reporter/datadog_reporter.go

compact pprof, which removes duplicate locations, and shrinks the size of uploaded pprof files

reporter: compact pprofs

---

symbolication/datadog_uploader.go

Reduce error logs for local symbol upload by:
* Avoiding logging an error for short-lived executables
* Splitting symbol copy and symbol upload timeouts to give local upload more chance to succeed
Best reviewed commit by commit!
@DataDog/profiling-full-host

symbolication: reduce error logs for local symbol upload [PROF-10143]

---

tools/generate_release_notes.sh

account for the cases where there are no upstream changes, or there are no datadog changes.
also make the commit detection more robust.

tools/generate_release_notes: account for edge cases

---

.github/workflows/build.yml

Before:
```
Warning: Restore cache failed: Some specified paths were not resolved, unable to cache dependencies.
```
After:
```
Cache restored successfully
Cache restored from key: setup-go-Linux-ubuntu
```

build: fix go cache usage

---

symbolication/datadog_uploader.go

Add symbol_source, origin, origin_version and filename to elf symbol uploads.
Remove platform since it's not used on backend side.

[PROF-10235] Add new metadata fields to elf symbol upload

---

.github/workflows/release.yml
Dockerfile.release
docker/Dockerfile.release
docker/entrypoint.sh

Container image is published to: https://github.com/DataDog/otel-profiling-agent/pkgs/container/otel-profiling-agent
Tested locally and the agent is running just fine:
```
time="2024-08-12T15:15:44Z" level=info msg="Starting OTEL profiling agent nayef/dockerfile+a7538d1.10353767468 (revision head-a7538d1a, build timestamp 1723472983)"
```
Jira: https://datadoghq.atlassian.net/browse/PROF-10354

release: build multi-arch docker image

---

go.mod
go.sum
reporter/datadog_reporter.go
symbolication/datadog_uploader.go

Update compression to zstd for profile and symbol upload with the goal of reducing network traffic.
Since we're sending a multi-part attachment with a small event (metadata) and a large file (pprof/symbols), with our current backend implementation, it's preferable to only compress the large payload to reduce costs.
However, since handling a compressed file is only supported for profiles and not symbols, we:
* Compress the pprof file in zstd (previously gzip) for profiles.
* Compress the whole HTTP payload for symbols in zstd (previously gzip).
@DataDog/profiling-full-host 
https://datadoghq.atlassian.net/browse/PROF-10408

uploads: update compression to zstd

---

libpf/pfelf/pfelf.go
symbolication/datadog_uploader.go

Bazel built Go binairies have their GNU build ID stripped, and their Go build ID set to the string "redacted"
See https://github.com/bazelbuild/rules_go/blob/199d8e4827f87d382a85febd0148c1b42fa949cc/go/private/actions/link.bzl#L174
In that case, we want to able to rely on the file hash, for this reason we:
- modify the function to get go build ID to consider that "redacted" is equivalent to not having a build ID
- still upload debug symbols even if they don't contain a GNU build id or a Go build ID (they'll always contain a file hash, that we will be using for symbolication in that case).
The underlying goal is to allow remote symbolication with local symbol upload to work seamless for Go binaries built with Bazel
@DataDog/profiling-full-host

symbolication: allow symbol upload for Bazel-built Go binairies

---

.github/workflows/build.yml
.github/workflows/pre-release.yaml

currently, the publish job, although not used at all by the release workflow, is imported as part of the build.yaml import (for the side effect of importing lint, tests and build jobs).
however, this is causing an issue since we switched the default permissions to contents/packages read instead of write. as the publish job requires the write permission, however, build.yaml is imported with the standard permissions, causing the following error:
The workflow is not valid. .github/workflows/release.yml (Line: 9, Col: 3): Error calling workflow 'DataDog/otel-profiling-agent/.github/workflows/build.yml@5d1ecca8fa1333159fd6eac689aec181057efc35'. The nested job 'publish' is requesting 'contents: write, packages: write', but is only allowed 'contents: read, packages: read'.
To fix this, we create …

github: fix workflow permissions error
